### ISSUE TITLE
Missing code: tools

### ISSUE THREAD

**Issue by chandayh** [YuYang0901/CLIP-spurious-finetune#1]
Dear authors,
Thank you for your work! I am very interested and impressed by this method. However as I tried to run the code, it seems the [launch spurious detection part](https://github.com/YuYang0901/CLIP-spurious-finetune#run-experiments) was missing. There's no such folder/package called `tools`. Could you please have a look? Thank you!

**Comment by YuYang0901** [comment]
Hello @chandayh ,

Thank you for your interest in our work and for pointing out the issue. I've just pushed a new commit that addresses the missing 'tools' folder for the spurious detection part. Please pull the latest version of the repository and check if it resolves your concern.

If you encounter any other issues or have further questions, don't hesitate to let me know. 

Best,
Yu
