### ISSUE TITLE
Missing csv file for inference

### ISSUE THREAD

**Issue by chq1155** [YuYang0901/CLIP-spurious-finetune#3]
Dear Yu,

Hope this email finds you well. I am writing to inquire a code issue regarding the paper 'Mitigating Spurious Correlations in Multi-modal Models during Fine-tuning'. 

In the inference script, (https://github.com/YuYang0901/CLIP-spurious-finetune/blob/main/tools/explain_predictions_imagenet.py#L4), I found that there should be a .csv file for prediction statistics, which is essential for obtaining the spurious correlation samples. Would you please check it and see if the csv file can be provided?

Many thanks for your help!

Best regards,

**Comment by YuYang0901** [comment]
Hi @chq1155 

The .csv file for prediction statistics is now available: https://github.com/YuYang0901/CLIP-spurious-finetune/blob/main/data/imagenet_rn50.csv. 

I hope this helps with your work!
