### ISSUE TITLE
How is GradCAM figure drawed?

### ISSUE THREAD

**Issue by yic20** [YuYang0901/CLIP-spurious-finetune#4]
Excellent work!
Could you please provide the code to draw GradCAM Figure 4-5 in your paper?

**Comment by YuYang0901** [comment]
Hello @yic20,

Thank you for your kind words and interest in our work!

To generate the GradCAM visualizations in Figures 4 and 5, we used the script `tools/explain_predictions_imagenet.py` for individual visualizations in the grid. After generating these individual visualizations, we post-edited them to combine them into the final figures presented in the paper. 

I hope this answers your question!
